version: 2.1
# How-to for Automated Smoke-test or code checking before deployment
jobs:
  smoke_test:
      docker:
        - image: alpine:latest
      steps:
        - run: apk add --update curl
        - run:
            name: smoke test.
            command: |
              URL="https://blog.udacity.com/"
              if curl -s --head ${URL} # test if blog.udacity. com exists
              then
               return 0
              else
               return 1
              fi

workflows:
  my_workflow:
    jobs:
      - smoke_test:
          requires:
            - configure_infrastructure